### PR TITLE
chore: support --cache-from arg

### PR DESCRIPTION
**Pull request by appleboy**
Improve docker build speed. See the repo: https://github.com/go-training/docker-in-github-actions-vs-drone

```dockerfile
FROM golang:1.14-alpine

LABEL maintainer="Bo-Yi Wu <appleboy.tw@gmail.com>"

RUN apk add bash ca-certificates git gcc g++ libc-dev
WORKDIR /app
# Force the go compiler to use modules
ENV GO111MODULE=on
# We want to populate the module cache based on the go.{mod,sum} files.
COPY go.mod .
COPY go.sum .
COPY main.go .

ENV GOOS=linux
ENV GOARCH=amd64
RUN go build -o /app -tags netgo -ldflags '-w -extldflags "-static"' .

CMD ["/app"]
```

## GitHub Actions

```yml
- name: build and push image
  uses: docker/build-push-action@v1
  with:
    username: ${{ secrets.DOCKER_USERNAME }}
    password: ${{ secrets.DOCKER_PASSWORD }}
    repository: appleboy/gin-docker-demo
    dockerfile: Dockerfile
    always_pull: true
    tags: latest
```

## Drone CI

```yml
- name: publish
  pull: always
  image: plugins/docker:linux-amd64
  settings:
    auto_tag: true
    cache_from: appleboy/gin-docker-demo
    daemon_off: false
    dockerfile: Dockerfile
    password:
      from_secret: docker_password
    repo: appleboy/gin-docker-demo
    username:
      from_secret: docker_username
  when:
    event:
      exclude:
      - pull_request
```

## Summary

build time

* GitHub Actions: 1m10s ([logs](https://github.com/go-training/docker-in-github-actions-vs-drone/runs/542876427?check_suite_focus=true))
* Drone CI: **17s** ([logs](https://cloud.drone.io/go-training/docker-in-github-actions-vs-drone/14/1/2))

### CODE REVIEW

**Comment by zappy-shu** [comment]
Apologies for getting back to you so slowly. Thanks for opening this PR, cache support is something we want to add.

One thing I'd suggest is to allow multiple `--cache-from`. The option can be used multiple times to give a list of cached images. As github actions doesn't allow for list or complex object inputs the way we've been handling these kind of options is by using a comma-delimited list (see how `--build-arg` is handled).

**Comment by appleboy** [comment]
@zappy-shu Done. See the commit https://github.com/docker/github-actions/pull/17/commits/f05453caffb843189c22e0d7be18fbd12c34474c

**Comment by zappy-shu** [comment]
Looks good. Could you also add a line to the build->inputs table in the readme: https://github.com/docker/github-actions#inputs-1

Afterwards I can merge and update the action include the new input

**Comment by appleboy** [comment]
@zappy-shu Done

**Comment by appleboy** [comment]
@zappy-shu Can you merge this feature? Maybe fix the https://github.com/docker/build-push-action/issues/7 issue?

**Pull request merged**
